artifact_uri: file:///C:/Users/34651/Desktop/MASTER/TFM/madrid_rental_prediction_ml/src/mlruns_initial_experiments/0/72ad1d0d704647e08c9af2291abc7ec1/artifacts
deleted_time: 1747474354973
end_time: 1747472401516
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: deleted
run_id: 72ad1d0d704647e08c9af2291abc7ec1
run_name: linear_regressor_1747472396
run_uuid: 72ad1d0d704647e08c9af2291abc7ec1
source_name: ''
source_type: 4
source_version: ''
start_time: 1747472396298
status: 3
tags: []
user_id: '34651'
