artifact_uri: file:///C:/Users/34651/Desktop/MASTER/TFM/madrid_rental_prediction_ml/src/mlruns_initial_experiments/0/55ddc603089843e4b307c3052c4f4aa4/artifacts
end_time: 1747472380594
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 55ddc603089843e4b307c3052c4f4aa4
run_name: KNN_Model
run_uuid: 55ddc603089843e4b307c3052c4f4aa4
source_name: ''
source_type: 4
source_version: ''
start_time: 1747472364191
status: 3
tags: []
user_id: '34651'
