artifact_uri: file:///C:/Users/34651/Desktop/MASTER/TFM/madrid_rental_prediction_ml/src/mlruns_initial_experiments/995424426293163870/8edc8a0ad88d4ee68fa6a079bcb775f9/artifacts
end_time: 1747132747533
entry_point_name: ''
experiment_id: '995424426293163870'
lifecycle_stage: active
run_id: 8edc8a0ad88d4ee68fa6a079bcb775f9
run_name: linear_regressor_7
run_uuid: 8edc8a0ad88d4ee68fa6a079bcb775f9
source_name: ''
source_type: 4
source_version: ''
start_time: 1747132745334
status: 4
tags: []
user_id: '34651'
