artifact_uri: file:///C:/Users/34651/Desktop/MASTER/TFM/madrid_rental_prediction_ml/src/mlruns_initial_experiments/0/65597bacb5094083916e134fe7b784f2/artifacts
end_time: 1747472814521
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 65597bacb5094083916e134fe7b784f2
run_name: KNN_Model
run_uuid: 65597bacb5094083916e134fe7b784f2
source_name: ''
source_type: 4
source_version: ''
start_time: 1747472802310
status: 3
tags: []
user_id: '34651'
