artifact_uri: file:///C:/Users/34651/Desktop/MASTER/TFM/madrid_rental_prediction_ml/src/mlruns_initial_experiments/0/ac2024d0cb6844dcae2a4121f6104049/artifacts
deleted_time: 1747474354963
end_time: 1747218940317
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: deleted
run_id: ac2024d0cb6844dcae2a4121f6104049
run_name: svm_regressor_1747218295
run_uuid: ac2024d0cb6844dcae2a4121f6104049
source_name: ''
source_type: 4
source_version: ''
start_time: 1747218295694
status: 3
tags: []
user_id: '34651'
