artifact_uri: file:///C:/Users/34651/Desktop/MASTER/TFM/madrid_rental_prediction_ml/src/mlruns_initial_experiments/0/d809e14f851f4c51b4be604e880bb939/artifacts
end_time: 1747210446824
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: d809e14f851f4c51b4be604e880bb939
run_name: random_forest_regressor_1747210386
run_uuid: d809e14f851f4c51b4be604e880bb939
source_name: ''
source_type: 4
source_version: ''
start_time: 1747210386648
status: 3
tags: []
user_id: '34651'
