artifact_uri: file:///C:/Users/34651/Desktop/MASTER/TFM/madrid_rental_prediction_ml/src/mlruns_initial_experiments/0/383b33b542a94bb4aac16cd4d048fc48/artifacts
end_time: 1747472085348
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 383b33b542a94bb4aac16cd4d048fc48
run_name: KNN_Model
run_uuid: 383b33b542a94bb4aac16cd4d048fc48
source_name: ''
source_type: 4
source_version: ''
start_time: 1747472042317
status: 3
tags: []
user_id: '34651'
