artifact_uri: file:///C:/Users/34651/Desktop/MASTER/TFM/madrid_rental_prediction_ml/src/mlruns_initial_experiments/0/f1c069889ed2443eaaefc942f7dc03ba/artifacts
end_time: 1747472017713
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: f1c069889ed2443eaaefc942f7dc03ba
run_name: xgboost_regressor_1747472000
run_uuid: f1c069889ed2443eaaefc942f7dc03ba
source_name: ''
source_type: 4
source_version: ''
start_time: 1747472000415
status: 3
tags: []
user_id: '34651'
