artifact_uri: file:///C:/Users/34651/Desktop/MASTER/TFM/madrid_rental_prediction_ml/src/mlruns_initial_experiments/0/05e9615122ae4256a0439849cea48bc8/artifacts
end_time: 1747217539519
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 05e9615122ae4256a0439849cea48bc8
run_name: xgboost_regressor_1747217513
run_uuid: 05e9615122ae4256a0439849cea48bc8
source_name: ''
source_type: 4
source_version: ''
start_time: 1747217514300
status: 3
tags: []
user_id: '34651'
