artifact_uri: file:///C:/Users/34651/Desktop/MASTER/TFM/madrid_rental_prediction_ml/src/mlruns_initial_experiments/0/3d80c3dc993049f0bd3d04647c809c6a/artifacts
end_time: 1747472612031
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 3d80c3dc993049f0bd3d04647c809c6a
run_name: xgboost_regressor_1747472596
run_uuid: 3d80c3dc993049f0bd3d04647c809c6a
source_name: ''
source_type: 4
source_version: ''
start_time: 1747472596212
status: 3
tags: []
user_id: '34651'
