artifact_uri: file:///C:/Users/34651/Desktop/MASTER/TFM/madrid_rental_prediction_ml/src/mlruns_initial_experiments/0/97c819a334a644a3add4234ee1f8efaa/artifacts
end_time: 1747319820061
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 97c819a334a644a3add4234ee1f8efaa
run_name: KNN_Model
run_uuid: 97c819a334a644a3add4234ee1f8efaa
source_name: ''
source_type: 4
source_version: ''
start_time: 1747319800094
status: 3
tags: []
user_id: '34651'
