artifact_uri: file:///C:/Users/34651/Desktop/MASTER/TFM/madrid_rental_prediction_ml/src/mlruns_initial_experiments/0/8ef0202da0cc4ce2a02129a71238c07b/artifacts
end_time: 1747217795359
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 8ef0202da0cc4ce2a02129a71238c07b
run_name: xgboost_regressor_1747217775
run_uuid: 8ef0202da0cc4ce2a02129a71238c07b
source_name: ''
source_type: 4
source_version: ''
start_time: 1747217775263
status: 3
tags: []
user_id: '34651'
