artifact_uri: file:///C:/Users/34651/Desktop/MASTER/TFM/madrid_rental_prediction_ml/src/mlruns_initial_experiments/0/37324476fd1f4a0db932ee0ecc9afc35/artifacts
deleted_time: 1747220819756
end_time: 1747134227069
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: deleted
run_id: 37324476fd1f4a0db932ee0ecc9afc35
run_name: judicious-finch-385
run_uuid: 37324476fd1f4a0db932ee0ecc9afc35
source_name: ''
source_type: 4
source_version: ''
start_time: 1747134219170
status: 3
tags: []
user_id: '34651'
