artifact_uri: file:///C:/Users/34651/Desktop/MASTER/TFM/madrid_rental_prediction_ml/src/mlruns_initial_experiments/0/878a9128437d42739ee05cd94e3ed5af/artifacts
end_time: 1747320154390
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 878a9128437d42739ee05cd94e3ed5af
run_name: KNN_Model
run_uuid: 878a9128437d42739ee05cd94e3ed5af
source_name: ''
source_type: 4
source_version: ''
start_time: 1747320086446
status: 3
tags: []
user_id: '34651'
