artifact_uri: file:///C:/Users/34651/Desktop/MASTER/TFM/madrid_rental_prediction_ml/src/mlruns_initial_experiments/0/0cbcd98e4b0c49218c3ad3538bbcf458/artifacts
end_time: 1747469614062
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 0cbcd98e4b0c49218c3ad3538bbcf458
run_name: KNN_Model
run_uuid: 0cbcd98e4b0c49218c3ad3538bbcf458
source_name: ''
source_type: 4
source_version: ''
start_time: 1747469590957
status: 3
tags: []
user_id: '34651'
