digest: 1e373d58
name: dataset
profile: '{"num_rows": 18399, "num_elements": 331182}'
schema: '{"mlflow_colspec": [{"type": "double", "name": "CONSTRUCTEDAREA", "required":
  true}, {"type": "long", "name": "HASTERRACE", "required": true}, {"type": "long",
  "name": "HASLIFT", "required": true}, {"type": "long", "name": "ISPARKINGSPACEINCLUDEDINPRICE",
  "required": true}, {"type": "double", "name": "ROOMNUMBER", "required": true}, {"type":
  "double", "name": "BATHNUMBER", "required": true}, {"type": "long", "name": "HASSWIMMINGPOOL",
  "required": true}, {"type": "long", "name": "HASGARDEN", "required": true}, {"type":
  "long", "name": "ISINTOPFLOOR", "required": true}, {"type": "double", "name": "DISTANCE_TO_CITY_CENTER",
  "required": true}, {"type": "double", "name": "DISTANCE_TO_METRO", "required": true},
  {"type": "double", "name": "DISTANCE_TO_CASTELLANA", "required": true}, {"type":
  "double", "name": "CADMAXBUILDINGFLOOR", "required": true}, {"type": "double", "name":
  "FLOORCLEAN", "required": true}, {"type": "long", "name": "PERIOD_201803", "required":
  true}, {"type": "long", "name": "PERIOD_201806", "required": true}, {"type": "long",
  "name": "PERIOD_201809", "required": true}, {"type": "long", "name": "PERIOD_201812",
  "required": true}]}'
source: '{"tags": {"mlflow.user": "34651", "mlflow.source.name": "C:\\Users\\34651\\Desktop\\MASTER\\TFM\\madrid_rental_prediction_ml\\src\\train_models.py",
  "mlflow.source.type": "LOCAL", "mlflow.source.git.commit": "39c06d32ce360a20c566c89758a86c2e31cd462d"}}'
source_type: code
