artifact_location: file:///C:/Users/34651/Desktop/MASTER/TFM/madrid_rental_prediction_ml/src/mlruns_initial_experiments/0
creation_time: 1747129455441
experiment_id: '0'
last_update_time: 1747129455441
lifecycle_stage: active
name: Default
