artifact_uri: file:///C:/Users/34651/Desktop/MASTER/TFM/madrid_rental_prediction_ml/src/mlruns_initial_experiments/0/89f9524e78094e5db33f6b8c9acfcb11/artifacts
deleted_time: 1747220819740
end_time: 1747209772509
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: deleted
run_id: 89f9524e78094e5db33f6b8c9acfcb11
run_name: random_forest_regressor_1747209765
run_uuid: 89f9524e78094e5db33f6b8c9acfcb11
source_name: ''
source_type: 4
source_version: ''
start_time: 1747209766365
status: 4
tags: []
user_id: '34651'
